load('@bazel_tools//tools/build_defs/repo:git.bzl', 'git_repository')
git_repository(
    name = "trpc_cpp",
    remote = "https://git.woa.com/trpc-cpp/open-source/trpc-cpp.git",
    branch = "master",
)
load("@trpc_cpp//trpc:workspace.bzl", "trpc_workspace")

trpc_workspace()

local_repository(
    name = "proto",
    path = "./proto",
)