// Code generated by trpc-go/trpc-cmdline {{ .TRPCCmdlineVersion }}. DO NOT EDIT.
// source: {{.Protofile}}

{{- /* .Protofile example: file1.fbs */}}
{{- /* $domainName .Domain example: trpc.group */}}

{{ $domainName := .Domain }}
{{- $serviceSuffix := "" -}}
{{- if not .NoServiceSuffix }}
    {{- $serviceSuffix = "Service" }}
{{- end }}

{{- /* $pkgName .PackageName example: trpc.testapp.testserver */}}
{{- /* $goPkgName example: trpc_testapp_testserver */}}
{{- /* $appName example: testapp */}}
{{- /* $serverName example: testserver */}}
{{- /* $protocol example: "trpc" */}}
{{- /* $fbsfile example: "file1.fbs" */}}
{{- /* $goPkgOption example: "trpc.group/trpcprotocol/testapp/testserver/greeter" */}}
{{- /* $goPkgName example: "greeter" */}}

{{ $pkgName := .PackageName -}}
{{ $goPkgName := .PackageName|gopkg -}}
{{ $appName := .AppName -}}
{{ $serverName := .ServerName -}}
{{ $protocol := .Protocol -}}
{{ $fbsfile := .Protofile -}}
{{- $goPkgOption := "" -}}
{{- with .FileOptions.go_package -}}
  {{- $goPkgOption = . -}}
  {{- $goPkgName = (splitList "/" $goPkgOption)|last|gopkg -}}
{{- end -}}
{{- $importStream := false }}
{{- $existRESTfulHTTPRule := false }}
{{- range $service := .Services }}
    {{- range $rpc := $service.RPC }}
        {{- if ne (len .RESTfulAPIInfo.ContentList) 0 }}
            {{- $existRESTfulHTTPRule = true}}
        {{- end }}
        {{- if or $rpc.ClientStreaming $rpc.ServerStreaming }}
            {{- $importStream = true }}
        {{- end }}
    {{- end }}
{{- end }}

{{- /* $goPkgName example: "greeter" */}}
package {{ $goPkgName }}

import (
	"context"
	"fmt"

	_ "{{ $domainName }}/trpc-go/trpc-go"
	_ "{{ $domainName }}/trpc-go/trpc-go/http"

    {{ if $existRESTfulHTTPRule }}
    "{{ $domainName }}/trpc-go/trpc-go/restful"
	{{ end }}

   	{{ if and (ne .Protocol "trpc") (ne .Protocol "http") }}
    "{{ $domainName }}/trpc-go/trpc-codec/{{.Protocol}}"
   	{{ end }}

    "{{ $domainName }}/trpc-go/trpc-go/server"
    "{{ $domainName }}/trpc-go/trpc-go/client"
    "{{ $domainName }}/trpc-go/trpc-go/codec"
    {{- if $importStream }}
    "{{ $domainName }}/trpc-go/trpc-go/stream"
    {{- end }}

{{- /* .Imports example: "trpc.group/trpcprotocol/testapp/testserver2" */}}
    {{ range .Imports }}
    {{ if ne $goPkgName . }}
    {{ if contains . ";" }}
    {{ $val := (splitList ";" .) }}
    {{ index $val 1}} "{{index $val 0}}"
    {{ else }}
    "{{- . -}}"
    {{ end }}
    {{ end }}
    {{ end }}
	flatbuffers "github.com/google/flatbuffers/go" 
)

/* ************************************ Service Definition ************************************ */

{{- /* $svrName example: Greeter */}}
{{- /* $svrNameCamelCase example: Greeter */}}
{{ range $service := .Services }}
{{- $svrName := $service.Name -}}
{{- $svrNameCamelCase := $service.Name|camelcase -}}

{{- $serviceStream := false }}
{{- range $rpc := $service.RPC }}
{{- if or $rpc.ClientStreaming $rpc.ServerStreaming }}
{{- $serviceStream = true }}
{{- end }}
{{- end }}

{{- /* $svrNameCamelCase example: Greeter */}}
// {{$svrNameCamelCase}}{{$serviceSuffix}} defines service
type {{$svrNameCamelCase}}{{$serviceSuffix}} interface {
	{{- /* $rpcName example: SayHello */}}
	{{- /* .RequestType example: HelloRequest */}}
	{{- /* .ResponseType example: HelloReply */}}
	{{ range $rpc := $service.RPC }}
	{{- $rpcName := .Name | camelcase -}}
	{{- /* $rpcReqType example: HelloRequest */}}
	{{- $rpcReqType := (simplify (gofulltype .RequestType $.FileDescriptor) $goPkgName)|export }}
	{{- /* $rpcRspType example: HelloReply */}}
	{{- $rpcRspType := (simplify (gofulltype .ResponseType $.FileDescriptor) $goPkgName)|export }}
	{{ with .LeadingComments }}// {{$rpcName}} {{.}}{{ end }}
    {{- if $rpc.ClientStreaming }}
	{{- /* SayHello(Greeter_SayHelloServer) error  */}}
    {{$rpcName}}({{$svrNameCamelCase}}_{{$rpcName}}Server) error {{ with .TrailingComments}}// {{.}}{{ end }}
    {{- else }}
    {{- if $rpc.ServerStreaming }}
	{{- /* SayHello(*HelloRequest, Greeter_SayHelloServerStreamServer) error  */}}
    {{$rpcName}}(*{{$rpcReqType}}, {{$svrNameCamelCase}}_{{$rpcName}}Server) error {{ with .TrailingComments}}// {{.}}{{ end }}
    {{- else }}
	{{- /* SayHello(ctx context.Context, req *HelloRequest) (*flatbuffers.Builder, error) */}}
    {{$rpcName}}(ctx context.Context, req *{{$rpcReqType}}) (*flatbuffers.Builder, error) {{ with .TrailingComments}}// {{.}}{{ end }}
    {{- end }}
    {{- end }}
    {{ end -}}
}

{{range $service.RPC -}}
{{- /* $rpcName example: SayHello */}}
{{- $rpcName := .Name | camelcase -}}
{{- $rpcReqType := (simplify (gofulltype .RequestType $.FileDescriptor) $goPkgName)|export }}
{{- $rpcRspType := (simplify (gofulltype .ResponseType $.FileDescriptor) $goPkgName)|export }}
{{- if and (ne .ClientStreaming true) (ne .ServerStreaming true) }}
{{- /* func GreeterService_SayHello_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (..) */}}
func {{$svrNameCamelCase}}{{$serviceSuffix}}_{{$rpcName}}_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	{{- /* req := &HelloRequest{} */}}
    req := &{{$rpcReqType}}{}
	filters, err := f(req)
    if err != nil {
    	return nil, err
    }

	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		{{- /* return svr.(GreeterServuce).SayHello(ctx, reqbody.(*HelloRequest)) */}}
		return svr.({{$svrNameCamelCase}}{{$serviceSuffix}}).{{$rpcName}}(ctx, reqbody.(*{{$rpcReqType}}))
	}

    {{ if eq $protocol "grpc" }}
    // get req from ctx
    grpcData := ctx.Value(grpc.ContextKeyHeader).(*grpc.Header)
    req = grpcData.Req.(*{{$rpcReqType}})
    {{ end }}

    value, err := filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	rsp, ok := value.(*flatbuffers.Builder)
	if !ok {
	    return nil, fmt.Errorf("unknow rsp value type: %T", value)
	}

    {{ if eq $protocol "grpc" }}
    // set rsp to ctx, and set rsp empty
    grpcData.Rsp = rsp
    rsp = &flatbuffers.Builder{}
    {{ end }}

	return rsp, nil
}
{{- else }}
{{- /* func GreeterService_SayHelloServerStream_Handler(srv interface{}, stream server.Stream) error { */}}
func {{$svrNameCamelCase}}{{$serviceSuffix}}_{{$rpcName}}_Handler(srv interface{}, stream server.Stream) error {
    {{- if (ne .ClientStreaming true) }}
	{{- /* m := new(HelloRequest) */}}
    m := new({{$rpcReqType}})
    if err := stream.RecvMsg(m); err != nil { return err }
	{{- /* return srv.(GreeterService).SayHelloServerStream(m, &greeterSayHelloServerStreamServer{stream}) */}}
    return srv.({{$svrNameCamelCase}}{{$serviceSuffix}}).{{$rpcName}}(m, &{{$svrNameCamelCase|untitle}}{{$rpcName}}Server{stream})
    {{- else }}
	{{- /* .ClientStreaming is true */}}
	{{- /* return srv.(GreeterService).SayHelloServerStream(&greeterSayHelloServerStreamServer{stream}) */}}
    return srv.({{$svrNameCamelCase}}{{$serviceSuffix}}).{{$rpcName}}(&{{$svrNameCamelCase|untitle}}{{$rpcName}}Server{stream})
    {{- end }}
}
{{ $genSend := .ServerStreaming }}
{{- $genSendAndClose := not .ServerStreaming -}}
{{- $genRecv := .ClientStreaming -}}
{{- /* type Greeter_SayHelloServerStreamServer interface { */}}
type {{$svrNameCamelCase}}_{{$rpcName}}Server interface {
    {{- if $genSend }}
	{{- /* Send(*flatbuffers.Builder) */}}
    Send(*flatbuffers.Builder) error
    {{- end }}
    {{- if $genSendAndClose }}
	{{- /* SendAndClose(*flatbuffers.Builder) */}}
    SendAndClose(*flatbuffers.Builder) error
    {{- end }}
    {{- if $genRecv }}
	{{- /* Recv() (*HelloRequest, error) */}}
    Recv() (*{{$rpcReqType}}, error)
    {{- end }}
    server.Stream
}
{{- /* type greeter_SayHelloServerStreamServer struct { */}}
type {{$svrNameCamelCase|untitle}}{{$rpcName}}Server struct {
    server.Stream
}

{{ if $genSend }}
{{- /* func (x *greeter_SayHelloServerStreamServer) Send(m *flatbuffers.Builder) */}}
func (x *{{$svrNameCamelCase|untitle}}{{$rpcName}}Server) Send(m *flatbuffers.Builder) error {
    return x.Stream.SendMsg(m)
}
{{ end }}

{{ if $genSendAndClose }}
{{- /* func(x *greeter_SayHelloServerStreamServer) SendAndClose(m *flatbuffers.Builder) */}}
func (x *{{$svrNameCamelCase|untitle}}{{$rpcName}}Server) SendAndClose(m *flatbuffers.Builder) error {
    return x.Stream.SendMsg(m)
}
{{ end }}

{{ if $genRecv }}
{{- /* func (x *greeter_SayHelloServerStreamServer) Recv() (*HelloRequest, error) { */}}
func (x *{{$svrNameCamelCase|untitle}}{{$rpcName}}Server) Recv() (*{{$rpcReqType}}, error) {
	{{- /* m := new(HelloRequest) */}}
    m := new({{$rpcReqType}})
    if err := x.Stream.RecvMsg(m); err != nil { return nil, err }
    return m, nil
}
{{ end }}
{{- end }}
{{end -}}

{{- range $service.RPC -}}
{{- $rpcName := .Name | camelcase }}
{{- if and (ne .ClientStreaming true ) (ne .ServerStreaming true ) }}

{{- $rpcReqType := (simplify (gofulltype .RequestType $.FileDescriptor) $goPkgName)|export }}
{{- $rpcRspType := (simplify (gofulltype .ResponseType $.FileDescriptor) $goPkgName)|export }}
{{- range $index, $content := .RESTfulAPIInfo.ContentList -}}
{{- if $content.RequestBody}}
// requestBody{{$svrNameCamelCase}}{{$serviceSuffix}}{{$rpcName}}RESTfulPath{{$index}} {{$content.Method}}: {{$content.PathTmpl}}
type requestBody{{$svrNameCamelCase}}{{$serviceSuffix}}{{$rpcName}}RESTfulPath{{$index}} struct{}

func (requestBody{{$svrNameCamelCase}}{{$serviceSuffix}}{{$rpcName}}RESTfulPath{{$index}}) Locate(message restful.ProtoMessage) interface{} {
	x := message.(*{{$rpcReqType}})
	{{- if eq $content.RequestBody "*"}}
	return x
	{{- else}}
	return &x.{{camelcase $content.RequestBody}}
	{{- end}}
}

func (requestBody{{$svrNameCamelCase}}{{$serviceSuffix}}{{$rpcName}}RESTfulPath{{$index}}) Body() string {
	return "{{$content.RequestBody}}"
}
{{- end -}}

{{- if $content.ResponseBody}}
// responseBody{{$svrNameCamelCase}}{{$serviceSuffix}}{{$rpcName}}RESTfulPath{{$index}} {{$content.Method}}: {{$content.PathTmpl}}
type responseBody{{$svrNameCamelCase}}{{$serviceSuffix}}{{$rpcName}}RESTfulPath{{$index}} struct{}

func (responseBody{{$svrNameCamelCase}}{{$serviceSuffix}}{{$rpcName}}RESTfulPath{{$index}}) Locate(message restful.ProtoMessage) interface{} {
	x := message.(*{{$rpcRspType}})
	{{- if eq $content.ResponseBody "*"}}
	return x
	{{- else}}
	return &x.{{camelcase $content.ResponseBody}}
	{{- end}}
}

func (responseBody{{$svrNameCamelCase}}{{$serviceSuffix}}{{$rpcName}}RESTfulPath{{$index}}) ResponseBody() string {
	return "{{$content.ResponseBody}}"
}

{{end}}
{{end}}
{{end}}
{{end}}

// {{$svrNameCamelCase}}Server_ServiceDesc descriptor for server.RegisterService
{{- /* var GreeterServer_ServiceDesc = server.ServiceDesc { */}}
var {{$svrNameCamelCase}}Server_ServiceDesc = server.ServiceDesc {
    ServiceName: "
    {{- if and $appName $serverName -}}
        trpc.{{$appName}}.{{$serverName}}.{{$service.Name -}}
    {{- else -}}
        {{- $pkgName}}.{{$service.Name -}}
    {{- end}}",
	{{- /* HandlerType: ((*GreeterService)(nil)), */}}
    HandlerType: ((*{{$svrNameCamelCase}}{{$serviceSuffix}})(nil)),
    {{- if $serviceStream }}
    StreamHandle: stream.NewStreamDispatcher(),
    {{- end }}
    Methods: []server.Method{
        {{- range $service.RPC}}
        {{- if and (ne .ClientStreaming true ) (ne .ServerStreaming true ) }}
        {{- $rpcName := .Name | camelcase }}
            {
				{{- /* Name: "/trpc.testapp.greeter.Greeter/SayHello", */}}
                Name: "{{.FullyQualifiedCmd}}",
				{{- /* Func: GreeterService_SayHello_handler, */}}
                Func: {{$svrNameCamelCase}}{{$serviceSuffix}}_{{$rpcName}}_Handler,
                {{if .RESTfulAPIInfo.ContentList }}
                {{- $rpcReqType := (simplify (gofulltype .RequestType $.FileDescriptor) $goPkgName)|export }}
                {{- $rpcRspType := (simplify (gofulltype .ResponseType $.FileDescriptor) $goPkgName)|export }}
                {{- $fullyQualifiedCmd := .FullyQualifiedCmd -}}
                Bindings: []*restful.Binding{
                    {{- range $index, $content := .RESTfulAPIInfo.ContentList -}}
                    {
                        Name:   "{{$fullyQualifiedCmd}}",
                        Input:  func() restful.ProtoMessage { return new({{$rpcReqType}}) },
                        Filter: func(svc interface{}, ctx context.Context, reqbody interface{}) (interface{}, error) {
                            return svc.({{$svrNameCamelCase}}{{$serviceSuffix}}).{{$rpcName}}(ctx, reqbody.(*{{$rpcReqType}}))
                        },
                        HTTPMethod: "{{$content.Method}}",
                        Pattern: restful.Enforce("{{$content.PathTmpl}}"),
                        Body: {{ if $content.RequestBody -}}
                                  requestBody{{$svrNameCamelCase}}{{$serviceSuffix}}{{$rpcName}}RESTfulPath{{$index}}{}
                              {{- else -}}
                                  nil
                              {{- end}},
                        ResponseBody: {{ if $content.ResponseBody -}}
                                          responseBody{{$svrNameCamelCase}}{{$serviceSuffix}}{{$rpcName}}RESTfulPath{{$index}}{}
                                      {{- else}}
                                          nil
                                      {{- end}},
                    },
                    {{- end -}}
                },
                {{ end }}
            },
        {{- end }}
        {{- end}}
        {{- range $service.RPCx }}
        {{- $rpcName := .Name | camelcase -}}
            {
                Name: "{{.FullyQualifiedCmd}}",
                Func: {{$svrNameCamelCase}}{{$serviceSuffix}}_{{$rpcName}}_Handler,
            },
        {{ end }}
    },
    {{- if $serviceStream }}
    Streams: []server.StreamDesc{
        {{- range $service.RPC}}
        {{- if or .ClientStreaming .ServerStreaming }}
        {{- $rpcName := .Name | camelcase }}
            {
                StreamName: "{{.FullyQualifiedCmd}}",
                Handler: {{$svrNameCamelCase}}{{$serviceSuffix}}_{{$rpcName}}_Handler,
                ServerStreams: {{ .ServerStreaming }},
            },
        {{- end }}
        {{- end}}
    },
    {{- end }}
}

// Register{{$svrNameCamelCase}}{{$serviceSuffix}} register service
{{- /* func RegisterGreeterService(s server.Service, svr GreeterService) { */}}
func Register{{$svrNameCamelCase}}{{$serviceSuffix}}(s server.Service, svr {{$svrNameCamelCase}}{{$serviceSuffix}}) {
    if err := s.Register(&{{$svrNameCamelCase}}Server_ServiceDesc, svr); err != nil {
        panic(fmt.Sprintf("{{$svrNameCamelCase}} register error:%v", err))
    }

    {{ if eq $protocol "grpc" }}
    // register service to grpc
    if err := grpc.Register({{$svrNameCamelCase}}Server_ServiceDesc.ServiceName,
    "{{$fbsfile}}",
    []grpc.RegisterMethodsInfo{
        {{- range $service.RPC}}
        {{- $rpcReqType := (simplify (gofulltype .RequestType $.FileDescriptor) $goPkgName)|export }}
        {{- $rpcRspType := (simplify (gofulltype .ResponseType $.FileDescriptor) $goPkgName)|export }}
        {{- if and (ne .ClientStreaming true ) (ne .ServerStreaming true ) }}
        {{- $rpcName := .Name | camelcase }}
            {
                Method: server.Method{
                    Name: "{{$rpcName}}",
                    Func: {{$svrNameCamelCase}}{{$serviceSuffix}}_{{$rpcName}}_Handler,
                },
                ReqType: reflect.TypeOf({{$rpcReqType}}{}),
                RspType: reflect.TypeOf({{$rpcRspType}}{}),
            },
        {{- end }}
        {{- end }}
    }); err != nil {
        panic(fmt.Sprintf("grpc register {{$svrNameCamelCase}} error:%v", err))
    }
    {{ end }}
}

{{ end }}

/* ************************************ Client Definition ************************************ */

{{ range $service := .Services }}
{{ $svrNameCamelCase := $service.Name | camelcase }}

// {{$svrNameCamelCase}}ClientProxy defines service client proxy
{{- /* type GreeterClientProxy interface { */}}
type {{$svrNameCamelCase}}ClientProxy interface {
    {{ range $rpc := $service.RPC}}
    {{- $rpcName := .Name | camelcase -}}
    {{- $rpcReqType := (simplify (gofulltype .RequestType $.FileDescriptor) $goPkgName)|export }}
   	{{- $rpcRspType := (simplify (gofulltype .ResponseType $.FileDescriptor) $goPkgName)|export }}
   	{{ with .LeadingComments }}// {{$rpcName}} {{.}}{{ end }}
    {{- if and (ne .ClientStreaming true) (ne .ServerStreaming true) }}
	{{- /* SayHello(ctx context.Context, req *flatbuffers.Builder, opts ...client.Option) (rsp *HelloReply, err error) */}}
    {{$rpcName}}(ctx context.Context, req *flatbuffers.Builder, opts ...client.Option) (rsp *{{$rpcRspType}}, err error) {{ with .TrailingComments }}// {{.}}{{ end }}
    {{- else }}
    {{- if .ClientStreaming }}
	{{- /* SayHelloClientStream(ctx context.Context, opts ...client.Option) (Greeter_SayHelloClientStreamClient, err error) */}}
    {{$rpcName}}(ctx context.Context, opts ...client.Option) ({{$svrNameCamelCase}}_{{$rpcName}}Client, error) {{ with .TrailingComments }}// {{.}}{{ end }}
    {{- else }}
	{{- /* SayHelloServerStream(ctx context.Context, req *flatbuffers.Builder, opts ...client.Option) (Greeter_SayHelloServerStreamClient, err error) */}}
    {{$rpcName}}(ctx context.Context, req *flatbuffers.Builder, opts ...client.Option) ({{$svrNameCamelCase}}_{{$rpcName}}Client, error) {{ with .TrailingComments }}// {{.}}{{ end }}
    {{- end }}
    {{- end }}
{{ end -}}
}

type {{$svrNameCamelCase}}ClientProxyImpl struct{
    client client.Client
    {{- if $importStream }}
    streamClient stream.Client
    {{- end }}
    opts []client.Option
}

var New{{$svrNameCamelCase}}ClientProxy = func(opts...client.Option) {{$svrNameCamelCase}}ClientProxy {
    {{- if $importStream }}
    return &{{$svrNameCamelCase}}ClientProxyImpl {client: client.DefaultClient, streamClient: stream.DefaultStreamClient, opts: opts}
    {{- else }}
    return &{{$svrNameCamelCase}}ClientProxyImpl {client: client.DefaultClient, opts: opts}
    {{- end }}
}

{{range $rpc := $service.RPC}}
{{- $rpcName := .Name | camelcase -}}
{{- $rpcReqType := (simplify (gofulltype .RequestType $.FileDescriptor) $goPkgName)|export }}
{{- $rpcRspType := (simplify (gofulltype .ResponseType $.FileDescriptor) $goPkgName)|export }}
{{ if and (ne .ClientStreaming true) (ne .ServerStreaming true) }}
func (c *{{$svrNameCamelCase}}ClientProxyImpl) {{$rpcName}}(ctx context.Context, req *flatbuffers.Builder, opts ...client.Option) (*{{$rpcRspType}}, error) {

    {{ if eq $protocol "grpc" }}
    // set req to ctx
	h := ctx.Value(grpc.ContextKeyHeader)
	var header *grpc.Header
	if h == nil {
		header = &grpc.Header{}
		ctx = context.WithValue(ctx, grpc.ContextKeyHeader, header)
	} else {
		var ok bool
		header, ok = h.(*grpc.Header)
		if !ok {
			return nil, errors.New(fmt.Sprintf("grpc header in context cannot be transferred to grpc.Header"))
		}
	}
	header.Req = req
	header.Rsp = &{{$rpcRspType}}{}
    {{ end }}

	ctx, msg := codec.WithCloneMessage(ctx)
    defer codec.PutBackMessage(msg)

	msg.WithClientRPCName("{{.FullyQualifiedCmd}}")
	msg.WithCalleeServiceName({{$svrNameCamelCase}}Server_ServiceDesc.ServiceName)
	msg.WithCalleeApp("{{$appName}}")
	msg.WithCalleeServer("{{$serverName}}")
	msg.WithCalleeService("{{$service.Name}}")
	msg.WithCalleeMethod("{{$rpcName}}")
	msg.WithSerializationType(codec.SerializationTypeFlatBuffer)

	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
    {{ if eq $protocol "grpc" }}
    callopts = append(callopts, client.WithProtocol("grpc"))
    {{ end }}
	rsp := &{{$rpcRspType}}{}

	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
	    return nil, err
	}

    {{ if eq $protocol "grpc" }}
    // get rsp from ctx
	*rsp = *header.Rsp.(*{{$rpcRspType}})
    {{ end }}

	return rsp, nil
}
{{ else }}
{{- if .ClientStreaming }}
func (c *{{$svrNameCamelCase}}ClientProxyImpl) {{$rpcName}}(ctx context.Context, opts ...client.Option) ({{$svrNameCamelCase}}_{{$rpcName}}Client, error) {
{{- else }}
func (c *{{$svrNameCamelCase}}ClientProxyImpl) {{$rpcName}}(ctx context.Context, req *flatbuffers.Builder, opts ...client.Option) ({{$svrNameCamelCase}}_{{$rpcName}}Client, error) {
{{- end }}

    ctx, msg := codec.WithCloneMessage(ctx)

	msg.WithClientRPCName("{{.FullyQualifiedCmd}}")
	msg.WithCalleeServiceName({{$svrNameCamelCase}}Server_ServiceDesc.ServiceName)
	msg.WithCalleeApp("{{$appName}}")
	msg.WithCalleeServer("{{$serverName}}")
	msg.WithCalleeService("{{$service.Name}}")
	msg.WithCalleeMethod("{{$rpcName}}")
	msg.WithSerializationType(codec.SerializationTypeFlatBuffer)

	clientStreamDesc := &stream.ClientStreamDesc{}
	clientStreamDesc.StreamName = "{{.FullyQualifiedCmd}}"
	clientStreamDesc.ClientStreams = true

    callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)

	stream, err := c.streamClient.NewStream(ctx, clientStreamDesc, "{{.FullyQualifiedCmd}}", callopts...)
    if err != nil {
		return nil, err
	}
	x := &{{$svrNameCamelCase|untitle}}{{$rpcName}}Client{stream}
	{{- if and (ne .ClientStreaming true) .ServerStreaming }}
	if err := x.ClientStream.SendMsg(req); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	{{- end }}

	return x, nil
}
{{ $genSend := .ClientStreaming }}
{{ $genRecv := .ServerStreaming }}
{{ $genCloseAndRecv := not .ServerStreaming }}
type {{$svrNameCamelCase}}_{{$rpcName}}Client interface {
	{{- if $genSend }}
	Send(*flatbuffers.Builder) error
	{{- end }}
	{{- if $genRecv }}
	Recv() (*{{$rpcRspType}}, error)
	{{- end }}
	{{- if $genCloseAndRecv }}
	CloseAndRecv() (*{{$rpcRspType}}, error)
	{{- end }}
	stream.ClientStream
}

type {{$svrNameCamelCase|untitle}}{{$rpcName}}Client struct {
	stream.ClientStream
}
{{ if $genSend }}
func (x *{{$svrNameCamelCase|untitle}}{{$rpcName}}Client) Send(m *flatbuffers.Builder) error {
	return x.ClientStream.SendMsg(m)
}
{{ end }}
{{ if $genRecv}}
func (x *{{$svrNameCamelCase|untitle}}{{$rpcName}}Client) Recv() (*{{$rpcRspType}}, error) {
	m := new({{$rpcRspType}})
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}
{{ end }}
{{ if $genCloseAndRecv }}
func (x *{{$svrNameCamelCase|untitle}}{{$rpcName}}Client) CloseAndRecv() (*{{$rpcRspType}}, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new({{$rpcRspType}})
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}
{{ end }}
{{ end }}
{{end}}

{{ end }}
